/**
 * This class is generated by jOOQ
 */
package tech.codingclub.helix.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Songlist extends org.jooq.impl.TableImpl<tech.codingclub.helix.tables.records.SonglistRecord> {

	private static final long serialVersionUID = -109923402;

	/**
	 * The singleton instance of <code>public.Songlist</code>
	 */
	public static final tech.codingclub.helix.tables.Songlist SONGLIST = new tech.codingclub.helix.tables.Songlist();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<tech.codingclub.helix.tables.records.SonglistRecord> getRecordType() {
		return tech.codingclub.helix.tables.records.SonglistRecord.class;
	}

	/**
	 * The column <code>public.Songlist.album_name</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.SonglistRecord, java.lang.String> ALBUM_NAME = createField("album_name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.Songlist.album_image_link</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.SonglistRecord, java.lang.String> ALBUM_IMAGE_LINK = createField("album_image_link", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.Songlist.cast</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.SonglistRecord, java.lang.String> CAST = createField("cast", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.Songlist.music_composer</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.SonglistRecord, java.lang.String> MUSIC_COMPOSER = createField("music_composer", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.Songlist.Song_name</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.SonglistRecord, java.lang.String> SONG_NAME = createField("Song_name", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * The column <code>public.Songlist.Song_download_link</code>.
	 */
	public final org.jooq.TableField<tech.codingclub.helix.tables.records.SonglistRecord, java.lang.String> SONG_DOWNLOAD_LINK = createField("Song_download_link", org.jooq.impl.SQLDataType.VARCHAR, this, "");

	/**
	 * Create a <code>public.Songlist</code> table reference
	 */
	public Songlist() {
		this("Songlist", null);
	}

	/**
	 * Create an aliased <code>public.Songlist</code> table reference
	 */
	public Songlist(java.lang.String alias) {
		this(alias, tech.codingclub.helix.tables.Songlist.SONGLIST);
	}

	private Songlist(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.SonglistRecord> aliased) {
		this(alias, aliased, null);
	}

	private Songlist(java.lang.String alias, org.jooq.Table<tech.codingclub.helix.tables.records.SonglistRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, tech.codingclub.helix.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public tech.codingclub.helix.tables.Songlist as(java.lang.String alias) {
		return new tech.codingclub.helix.tables.Songlist(alias, this);
	}

	/**
	 * Rename this table
	 */
	public tech.codingclub.helix.tables.Songlist rename(java.lang.String name) {
		return new tech.codingclub.helix.tables.Songlist(name, null);
	}
}
